### ISSUE TITLE
File format handling

### ISSUE THREAD

**Issue by jnooree** [seoklab/nurikit#13]
This is a tracking issue for the [File format handling](https://github.com/seoklab/nurikit/milestone/3) milestone.

```[tasklist]
### Format parsing
- [ ] https://github.com/seoklab/nurikit/issues/78
- [ ] https://github.com/seoklab/nurikit/issues/77
- [ ] https://github.com/seoklab/nurikit/issues/162
- [ ] https://github.com/seoklab/nurikit/issues/241
- [ ] FASTA parser
- [ ] https://github.com/seoklab/nurikit/pull/444
- [ ] https://github.com/seoklab/nurikit/pull/445
```

```[tasklist]
### Format writing
- [ ] https://github.com/seoklab/nurikit/issues/273
- [ ] https://github.com/seoklab/nurikit/issues/249
- [ ] https://github.com/seoklab/nurikit/issues/258
- [ ] FASTA writer
- [ ] https://github.com/seoklab/nurikit/pull/463
- [ ] PDBx/mmCIF writer
```
